## Загрузим нужные библиотеки

In [1]:
!pip install seaborn
!pip install  h3

Requirement already satisfied: seaborn in /root/miniconda3/lib/python3.9/site-packages (0.11.2)
Requirement already satisfied: matplotlib>=2.2 in /root/miniconda3/lib/python3.9/site-packages (from seaborn) (3.5.1)
Requirement already satisfied: scipy>=1.0 in /root/miniconda3/lib/python3.9/site-packages (from seaborn) (1.8.0)
Requirement already satisfied: numpy>=1.15 in /root/miniconda3/lib/python3.9/site-packages (from seaborn) (1.21.5)
Requirement already satisfied: pandas>=0.23 in /root/miniconda3/lib/python3.9/site-packages (from seaborn) (1.3.5)
Requirement already satisfied: fonttools>=4.22.0 in /root/miniconda3/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (4.31.2)
Requirement already satisfied: pillow>=6.2.0 in /root/miniconda3/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (9.0.1)
Requirement already satisfied: python-dateutil>=2.7 in /root/miniconda3/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in /root/miniconda3/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (3.0.7)
Requirement already satisfied: cycler>=0.10 in /root/miniconda3/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /root/miniconda3/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (1.4.2)
Requirement already satisfied: packaging>=20.0 in /root/miniconda3/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (21.3)
Requirement already satisfied: pytz>=2017.3 in /root/miniconda3/lib/python3.9/site-packages (from pandas>=0.23->seaborn) (2022.1)
Requirement already satisfied: six>=1.5 in /root/miniconda3/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib>=2.2->seaborn) (1.16.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/root/miniconda3/bin/python -m pip install --upgrade pip' command.
Requirement already satisfied: h3 in /root/miniconda3/lib/python3.9/site-packages (3.7.4)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/root/miniconda3/bin/python -m pip install --upgrade pip' command.

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from tqdm import tqdm
tqdm.pandas()
%matplotlib inline

In [3]:
df_train = pd.read_csv("./train_dataset_train.csv")
df_test = pd.read_csv("./test_dataset_test.csv")

In [4]:
df_test

,id,Дата,Время,Место,Улица,Дом,Дорога,Километр,Метр,Вид ДТП
0,490078911,31.01.2018,19:15:00,"Новгородская область, Великий Новгород",Нехинская ул,59,NaN,NaN,NaN,Столкновение
1,490055448,19.06.2019,10:15:00,"Новгородская область, Великий Новгород",Большая Московская ул,38,NaN,NaN,NaN,Столкновение
2,490054440,28.06.2019,03:00:00,"Новгородская область, Великий Новгород",NaN,NaN,NaN,NaN,NaN,Наезд на препятствие
3,490037847,01.02.2019,13:15:00,"Новгородская область, Великий Новгород",Колмовская наб,3,NaN,NaN,NaN,Наезд на препятствие
4,490037049,08.02.2019,10:35:00,"Новгородская область, Окуловский район",NaN,NaN,Нева Москва - Санкт-Петербург (основное направ...,471.0,900.0,Наезд на препятствие
...,...,...,...,...,...,...,...,...,...,...
6783,490014641,11.07.2020,23:15:00,"Новгородская область, Боровичский район, Боровичи",Коммунарная ул,1А,NaN,NaN,NaN,NaN
6784,490033115,12.01.2020,15:20:00,"Новгородская область, Окуловский район",NaN,NaN,Нева Москва - Санкт-Петербург (основное направ...,438.0,833.0,NaN
6785,490008221,04.09.2020,20:05:00,"Новгородская область, Новгородский район",NaN,NaN,"""Россия"" Москва - Тверь - Великий Новгород - С...",539.0,0.0,NaN
6786,490119585,11.11.2018,16:25:00,"Новгородская область, Окуловский район, Окуловка",Николая Николаева ул,53,NaN,NaN,NaN,Столкновение
6787,490109680,28.09.2018,12:45:00,"Новгородская область, Великий Новгород",Кочетова ул,23а,NaN,NaN,NaN,Столкновение

## Геокодирование

In [5]:
'''
#!pip install yandex_geocoder
from yandex_geocoder import Client
client = Client("111-111-111-111-1111")


df_train['x']=0
df_train['y']=0
df_test['x']=0
df_test['y']=0


for i in tqdm(df_test.index):
    df_test['x'].loc[i],df_test['y'].loc[i]=client.coordinates(df_test['Место'].loc[i]+' '+df_test['Улица'].fillna('').loc[i]+ ' дом '+df_test['Дом'].fillna('').loc[i])

for i in tqdm(df_train.index):
    df_train['x'].loc[i],df_train['y'].loc[i]=client.coordinates(df_train['Место'].loc[i]+' '+df_train['Улица'].fillna('').loc[i]+ ' дом '+df_train['Дом'].fillna('').loc[i])
    

df_test.to_pickle("./df_test.pkl")  
df_train.to_pickle("./df_train.pkl")  

'''

'\n#!pip install yandex_geocoder\nfrom yandex_geocoder import Client\nclient = Client("c0d403ab-e5be-4049-908c-8122a58acf23")\n\n\ndf_train[\'x\']=0\ndf_train[\'y\']=0\ndf_test[\'x\']=0\ndf_test[\'y\']=0\n\n\nfor i in tqdm(df_test.index):\n    df_test[\'x\'].loc[i],df_test[\'y\'].loc[i]=client.coordinates(df_test[\'Место\'].loc[i]+\' \'+df_test[\'Улица\'].fillna(\'\').loc[i]+ \' дом \'+df_test[\'Дом\'].fillna(\'\').loc[i])\n\nfor i in tqdm(df_train.index):\n    df_train[\'x\'].loc[i],df_train[\'y\'].loc[i]=client.coordinates(df_train[\'Место\'].loc[i]+\' \'+df_train[\'Улица\'].fillna(\'\').loc[i]+ \' дом \'+df_train[\'Дом\'].fillna(\'\').loc[i])\n    \n\ndf_test.to_pickle("./df_test.pkl")  \ndf_train.to_pickle("./df_train.pkl")  \n\n'

In [6]:
df_test=pd.read_pickle("./df_test.pkl")
df_train=pd.read_pickle("./df_train.pkl")
df_train

,id,Дата,Время,Место,Улица,Дом,Дорога,Километр,Метр,Вид ДТП,Погибло,Погибло детей,Ранено,Ранено детей,x,y
0,490103984,13.07.2018,17:35:00,"Новгородская область, Великий Новгород",Большая Санкт-Петербургская ул,88,NaN,NaN,NaN,Столкновение,0,0,0,0,31.269654,58.55244
1,490097169,11.05.2018,17:10:00,"Новгородская область, Великий Новгород",Большая Санкт-Петербургская ул,73,NaN,NaN,NaN,Столкновение,0,0,0,0,31.267229,58.552328
2,490031781,25.01.2020,14:44:00,"Новгородская область, Великий Новгород",Хутынская ул,29,NaN,NaN,NaN,NaN,0,0,0,0,31.317337,58.541085
3,490021246,11.05.2020,11:30:00,"Новгородская область, Новгородский район, Сави...",Вишнёвая ул,4,NaN,NaN,NaN,NaN,0,0,0,0,31.405435,58.581187
4,490041585,09.01.2019,01:45:00,"Новгородская область, Окуловский район",NaN,NaN,Нева Москва - Санкт-Петербург (основное направ...,430.0,5.0,Иной вид ДТП,0,0,0,0,33.297763,58.376532
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35766,490049248,15.05.2019,07:35:00,"Новгородская область, Великий Новгород",NaN,NaN,NaN,NaN,NaN,Столкновение,0,0,0,0,31.308039,58.529252
35767,490070258,15.10.2019,08:45:00,"Новгородская область, Великий Новгород",Пестовская ул,1,NaN,NaN,NaN,Столкновение,0,0,0,0,31.301158,58.531479
35768,490046086,10.03.2019,09:00:00,"Новгородская область, Старорусский район, Стар...",NaN,NaN,NaN,NaN,NaN,Наезд на стоящее ТС,0,0,0,0,31.355461,57.99072
35769,490007163,13.09.2020,05:40:00,"Новгородская область, Новгородский район",NaN,NaN,"""Россия"" Москва - Тверь - Великий Новгород - С...",544.0,870.0,NaN,0,0,0,0,31.308039,58.529252
35770,490079894,25.01.2018,18:45:00,"Новгородская область, Поддорский район",NaN,NaN,Шимск - Старая Русса - Локня - Невель,91.0,350.0,Наезд на стоящее ТС,0,0,0,0,31.114839,57.49121

## Перевод координат по H3 сетке

In [7]:
import h3

In [8]:
df_train['h3-3']=''
df_train['h3-4']=''
df_train['h3-5']=''
df_train['h3-6']=''
df_train['h3-7']=''
df_train['h3-8']=''


for i in tqdm(df_train.index):
    df_train['h3-3'].loc[i]= h3.geo_to_h3(df_train['y'].loc[i], df_train['x'].loc[i], 3)
    df_train['h3-4'].loc[i]= h3.geo_to_h3(df_train['y'].loc[i], df_train['x'].loc[i], 4)
    df_train['h3-5'].loc[i]= h3.geo_to_h3(df_train['y'].loc[i], df_train['x'].loc[i], 5)
    df_train['h3-6'].loc[i]= h3.geo_to_h3(df_train['y'].loc[i], df_train['x'].loc[i], 6)
    df_train['h3-7'].loc[i]= h3.geo_to_h3(df_train['y'].loc[i], df_train['x'].loc[i], 7)
    df_train['h3-8'].loc[i]= h3.geo_to_h3(df_train['y'].loc[i], df_train['x'].loc[i], 8)

  0% 0/35771 [00:00<?, ?it/s]/root/miniconda3/lib/python3.9/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
100% 35771/35771 [02:41<00:00, 221.27it/s]

In [9]:
df_test['h3-3']=''
df_test['h3-4']=''
df_test['h3-5']=''
df_test['h3-6']=''
df_test['h3-7']=''
df_test['h3-8']=''


for i in tqdm(df_test.index):
    df_test['h3-3'].loc[i] =h3.geo_to_h3(df_test['y'].loc[i], df_test['x'].loc[i], 3)
    df_test['h3-4'].loc[i] =h3.geo_to_h3(df_test['y'].loc[i], df_test['x'].loc[i], 4)
    df_test['h3-5'].loc[i] =h3.geo_to_h3(df_test['y'].loc[i], df_test['x'].loc[i], 5)
    df_test['h3-6'].loc[i] =h3.geo_to_h3(df_test['y'].loc[i], df_test['x'].loc[i], 6)
    df_test['h3-7'].loc[i] =h3.geo_to_h3(df_test['y'].loc[i], df_test['x'].loc[i], 7)
    df_test['h3-8'].loc[i] =h3.geo_to_h3(df_test['y'].loc[i], df_test['x'].loc[i], 8)

100% 6788/6788 [00:25<00:00, 269.75it/s]

In [10]:
df_train

,id,Дата,Время,Место,Улица,Дом,Дорога,Километр,Метр,Вид ДТП,...,Ранено,Ранено детей,x,y,h3-3,h3-4,h3-5,h3-6,h3-7,h3-8
0,490103984,13.07.2018,17:35:00,"Новгородская область, Великий Новгород",Большая Санкт-Петербургская ул,88,NaN,NaN,NaN,Столкновение,...,0,0,31.269654,58.55244,831115fffffffff,8411155ffffffff,85111543fffffff,86111542fffffff,87111542effffff,88111542ebfffff
1,490097169,11.05.2018,17:10:00,"Новгородская область, Великий Новгород",Большая Санкт-Петербургская ул,73,NaN,NaN,NaN,Столкновение,...,0,0,31.267229,58.552328,831115fffffffff,8411155ffffffff,85111543fffffff,86111542fffffff,87111542effffff,88111542ebfffff
2,490031781,25.01.2020,14:44:00,"Новгородская область, Великий Новгород",Хутынская ул,29,NaN,NaN,NaN,NaN,...,0,0,31.317337,58.541085,831115fffffffff,8411155ffffffff,85111543fffffff,86111542fffffff,87111542affffff,88111542a7fffff
3,490021246,11.05.2020,11:30:00,"Новгородская область, Новгородский район, Сави...",Вишнёвая ул,4,NaN,NaN,NaN,NaN,...,0,0,31.405435,58.581187,831115fffffffff,8411155ffffffff,85111547fffffff,861115477ffffff,871115454ffffff,8811154727fffff
4,490041585,09.01.2019,01:45:00,"Новгородская область, Окуловский район",NaN,NaN,Нева Москва - Санкт-Петербург (основное направ...,430.0,5.0,Иной вид ДТП,...,0,0,33.297763,58.376532,831113fffffffff,8411115ffffffff,8511114bfffffff,86111149fffffff,87111149dffffff,88111149d9fffff
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35766,490049248,15.05.2019,07:35:00,"Новгородская область, Великий Новгород",NaN,NaN,NaN,NaN,NaN,Столкновение,...,0,0,31.308039,58.529252,831115fffffffff,8411155ffffffff,85111543fffffff,861115407ffffff,871115405ffffff,8811154019fffff
35767,490070258,15.10.2019,08:45:00,"Новгородская область, Великий Новгород",Пестовская ул,1,NaN,NaN,NaN,Столкновение,...,0,0,31.301158,58.531479,831115fffffffff,8411155ffffffff,85111543fffffff,861115407ffffff,871115405ffffff,8811154053fffff
35768,490046086,10.03.2019,09:00:00,"Новгородская область, Старорусский район, Стар...",NaN,NaN,NaN,NaN,NaN,Наезд на стоящее ТС,...,0,0,31.355461,57.99072,831110fffffffff,8411109ffffffff,8511109bfffffff,86111099fffffff,87111099dffffff,88111099d1fffff
35769,490007163,13.09.2020,05:40:00,"Новгородская область, Новгородский район",NaN,NaN,"""Россия"" Москва - Тверь - Великий Новгород - С...",544.0,870.0,NaN,...,0,0,31.308039,58.529252,831115fffffffff,8411155ffffffff,85111543fffffff,861115407ffffff,871115405ffffff,8811154019fffff
35770,490079894,25.01.2018,18:45:00,"Новгородская область, Поддорский район",NaN,NaN,Шимск - Старая Русса - Локня - Невель,91.0,350.0,Наезд на стоящее ТС,...,0,0,31.114839,57.49121,831116fffffffff,841116bffffffff,851116a3fffffff,861116a0fffffff,871116a0affffff,881116a0a3fffff

In [11]:
#h3.h3_to_geo('8a430c340007fff')

Добавим пару новых столбцов

In [12]:
df_train["Дата"] = pd.to_datetime(df_train["Дата"].astype(str)+' '+df_train["Время"].astype(str))
df_train["day"]=df_train["Дата"].dt.day
df_train["day_of_week"]=df_train["Дата"].dt.day_of_week
df_train["day_of_year"]=df_train["Дата"].dt.day_of_year
df_train["hour"]=df_train["Дата"].dt.hour

In [13]:
df_test["Дата"] = pd.to_datetime(df_test["Дата"])
df_test["day"]=df_test["Дата"].dt.day
df_test["day_of_week"]=df_test["Дата"].dt.day_of_week
df_test["day_of_year"]=df_test["Дата"].dt.day_of_year
df_test["hour"]=df_test["Дата"].dt.hour
df_test

,id,Дата,Время,Место,Улица,Дом,Дорога,Километр,Метр,Вид ДТП,...,h3-3,h3-4,h3-5,h3-6,h3-7,h3-8,day,day_of_week,day_of_year,hour
0,490078911,2018-01-31,19:15:00,"Новгородская область, Великий Новгород",Нехинская ул,59,NaN,NaN,NaN,Столкновение,...,831115fffffffff,8411155ffffffff,85111543fffffff,861115427ffffff,871115420ffffff,8811154201fffff,31,2,31,0
1,490055448,2019-06-19,10:15:00,"Новгородская область, Великий Новгород",Большая Московская ул,38,NaN,NaN,NaN,Столкновение,...,831115fffffffff,8411155ffffffff,85111543fffffff,861115407ffffff,871115405ffffff,8811154055fffff,19,2,170,0
2,490054440,2019-06-28,03:00:00,"Новгородская область, Великий Новгород",NaN,NaN,NaN,NaN,NaN,Наезд на препятствие,...,831115fffffffff,8411155ffffffff,85111543fffffff,861115407ffffff,871115405ffffff,8811154019fffff,28,4,179,0
3,490037847,2019-01-02,13:15:00,"Новгородская область, Великий Новгород",Колмовская наб,3,NaN,NaN,NaN,Наезд на препятствие,...,831115fffffffff,8411155ffffffff,85111543fffffff,86111542fffffff,87111542effffff,88111542e1fffff,2,2,2,0
4,490037049,2019-08-02,10:35:00,"Новгородская область, Окуловский район",NaN,NaN,Нева Москва - Санкт-Петербург (основное направ...,471.0,900.0,Наезд на препятствие,...,831113fffffffff,8411115ffffffff,8511114bfffffff,86111149fffffff,87111149dffffff,88111149d9fffff,2,4,214,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6783,490014641,2020-11-07,23:15:00,"Новгородская область, Боровичский район, Боровичи",Коммунарная ул,1А,NaN,NaN,NaN,NaN,...,831113fffffffff,841113bffffffff,851113affffffff,861113ae7ffffff,871113ae0ffffff,881113ae09fffff,7,5,312,0
6784,490033115,2020-12-01,15:20:00,"Новгородская область, Окуловский район",NaN,NaN,Нева Москва - Санкт-Петербург (основное направ...,438.0,833.0,NaN,...,831113fffffffff,8411115ffffffff,8511114bfffffff,86111149fffffff,87111149dffffff,88111149d9fffff,1,1,336,0
6785,490008221,2020-04-09,20:05:00,"Новгородская область, Новгородский район",NaN,NaN,"""Россия"" Москва - Тверь - Великий Новгород - С...",539.0,0.0,NaN,...,831115fffffffff,8411155ffffffff,85111543fffffff,861115407ffffff,871115405ffffff,8811154019fffff,9,3,100,0
6786,490119585,2018-11-11,16:25:00,"Новгородская область, Окуловский район, Окуловка",Николая Николаева ул,53,NaN,NaN,NaN,Столкновение,...,831113fffffffff,8411115ffffffff,8511114bfffffff,861111487ffffff,87111148effffff,8811114833fffff,11,6,315,0
6787,490109680,2018-09-28,12:45:00,"Новгородская область, Великий Новгород",Кочетова ул,23а,NaN,NaN,NaN,Столкновение,...,831115fffffffff,8411155ffffffff,85111543fffffff,861115427ffffff,871115420ffffff,881115421dfffff,28,4,271,0

In [14]:
df_train['Вид ДТП'].value_counts()

Столкновение                                                                                                                       12649
Наезд на препятствие                                                                                                                4180
Наезд на стоящее ТС                                                                                                                 3992
Иной вид ДТП                                                                                                                        1106
Наезд на пешехода                                                                                                                   1023
Съезд с дороги                                                                                                                       959
Опрокидывание                                                                                                                        585
Наезд на животное                                                                                                                    356
Наезд на велосипедиста                                                                                                               294
Отбрасывание предмета (отсоединение колеса)                                                                                          184
Падение пассажира                                                                                                                    115
Наезд на внезапно возникшее препятствие                                                                                               56
Падение груза                                                                                                                         35
Возгорание вследствие технической неисправности движущегося или остановившегося ТС, участвующего в дорожном движении                  10
Наезд на лицо, не являющееся участником дорожного движения (иного участника ДТП), осуществляющее производство работ                    5
Наезд на лицо, не являющееся участником дорожного движения (иного участника ДТП), осуществляющее какую-либо другую деятельность        4
Наезд на лицо, не являющееся участником дорожного движения (иного участника ДТП), осуществляющее несение службы                        2
Name: Вид ДТП, dtype: int64

In [15]:
df_train

,id,Дата,Время,Место,Улица,Дом,Дорога,Километр,Метр,Вид ДТП,...,h3-3,h3-4,h3-5,h3-6,h3-7,h3-8,day,day_of_week,day_of_year,hour
0,490103984,2018-07-13 17:35:00,17:35:00,"Новгородская область, Великий Новгород",Большая Санкт-Петербургская ул,88,NaN,NaN,NaN,Столкновение,...,831115fffffffff,8411155ffffffff,85111543fffffff,86111542fffffff,87111542effffff,88111542ebfffff,13,4,194,17
1,490097169,2018-11-05 17:10:00,17:10:00,"Новгородская область, Великий Новгород",Большая Санкт-Петербургская ул,73,NaN,NaN,NaN,Столкновение,...,831115fffffffff,8411155ffffffff,85111543fffffff,86111542fffffff,87111542effffff,88111542ebfffff,5,0,309,17
2,490031781,2020-01-25 14:44:00,14:44:00,"Новгородская область, Великий Новгород",Хутынская ул,29,NaN,NaN,NaN,NaN,...,831115fffffffff,8411155ffffffff,85111543fffffff,86111542fffffff,87111542affffff,88111542a7fffff,25,5,25,14
3,490021246,2020-11-05 11:30:00,11:30:00,"Новгородская область, Новгородский район, Сави...",Вишнёвая ул,4,NaN,NaN,NaN,NaN,...,831115fffffffff,8411155ffffffff,85111547fffffff,861115477ffffff,871115454ffffff,8811154727fffff,5,3,310,11
4,490041585,2019-09-01 01:45:00,01:45:00,"Новгородская область, Окуловский район",NaN,NaN,Нева Москва - Санкт-Петербург (основное направ...,430.0,5.0,Иной вид ДТП,...,831113fffffffff,8411115ffffffff,8511114bfffffff,86111149fffffff,87111149dffffff,88111149d9fffff,1,6,244,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35766,490049248,2019-05-15 07:35:00,07:35:00,"Новгородская область, Великий Новгород",NaN,NaN,NaN,NaN,NaN,Столкновение,...,831115fffffffff,8411155ffffffff,85111543fffffff,861115407ffffff,871115405ffffff,8811154019fffff,15,2,135,7
35767,490070258,2019-10-15 08:45:00,08:45:00,"Новгородская область, Великий Новгород",Пестовская ул,1,NaN,NaN,NaN,Столкновение,...,831115fffffffff,8411155ffffffff,85111543fffffff,861115407ffffff,871115405ffffff,8811154053fffff,15,1,288,8
35768,490046086,2019-10-03 09:00:00,09:00:00,"Новгородская область, Старорусский район, Стар...",NaN,NaN,NaN,NaN,NaN,Наезд на стоящее ТС,...,831110fffffffff,8411109ffffffff,8511109bfffffff,86111099fffffff,87111099dffffff,88111099d1fffff,3,3,276,9
35769,490007163,2020-09-13 05:40:00,05:40:00,"Новгородская область, Новгородский район",NaN,NaN,"""Россия"" Москва - Тверь - Великий Новгород - С...",544.0,870.0,NaN,...,831115fffffffff,8411155ffffffff,85111543fffffff,861115407ffffff,871115405ffffff,8811154019fffff,13,6,257,5
35770,490079894,2018-01-25 18:45:00,18:45:00,"Новгородская область, Поддорский район",NaN,NaN,Шимск - Старая Русса - Локня - Невель,91.0,350.0,Наезд на стоящее ТС,...,831116fffffffff,841116bffffffff,851116a3fffffff,861116a0fffffff,871116a0affffff,881116a0a3fffff,25,3,25,18

In [16]:
df_test

,id,Дата,Время,Место,Улица,Дом,Дорога,Километр,Метр,Вид ДТП,...,h3-3,h3-4,h3-5,h3-6,h3-7,h3-8,day,day_of_week,day_of_year,hour
0,490078911,2018-01-31,19:15:00,"Новгородская область, Великий Новгород",Нехинская ул,59,NaN,NaN,NaN,Столкновение,...,831115fffffffff,8411155ffffffff,85111543fffffff,861115427ffffff,871115420ffffff,8811154201fffff,31,2,31,0
1,490055448,2019-06-19,10:15:00,"Новгородская область, Великий Новгород",Большая Московская ул,38,NaN,NaN,NaN,Столкновение,...,831115fffffffff,8411155ffffffff,85111543fffffff,861115407ffffff,871115405ffffff,8811154055fffff,19,2,170,0
2,490054440,2019-06-28,03:00:00,"Новгородская область, Великий Новгород",NaN,NaN,NaN,NaN,NaN,Наезд на препятствие,...,831115fffffffff,8411155ffffffff,85111543fffffff,861115407ffffff,871115405ffffff,8811154019fffff,28,4,179,0
3,490037847,2019-01-02,13:15:00,"Новгородская область, Великий Новгород",Колмовская наб,3,NaN,NaN,NaN,Наезд на препятствие,...,831115fffffffff,8411155ffffffff,85111543fffffff,86111542fffffff,87111542effffff,88111542e1fffff,2,2,2,0
4,490037049,2019-08-02,10:35:00,"Новгородская область, Окуловский район",NaN,NaN,Нева Москва - Санкт-Петербург (основное направ...,471.0,900.0,Наезд на препятствие,...,831113fffffffff,8411115ffffffff,8511114bfffffff,86111149fffffff,87111149dffffff,88111149d9fffff,2,4,214,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6783,490014641,2020-11-07,23:15:00,"Новгородская область, Боровичский район, Боровичи",Коммунарная ул,1А,NaN,NaN,NaN,NaN,...,831113fffffffff,841113bffffffff,851113affffffff,861113ae7ffffff,871113ae0ffffff,881113ae09fffff,7,5,312,0
6784,490033115,2020-12-01,15:20:00,"Новгородская область, Окуловский район",NaN,NaN,Нева Москва - Санкт-Петербург (основное направ...,438.0,833.0,NaN,...,831113fffffffff,8411115ffffffff,8511114bfffffff,86111149fffffff,87111149dffffff,88111149d9fffff,1,1,336,0
6785,490008221,2020-04-09,20:05:00,"Новгородская область, Новгородский район",NaN,NaN,"""Россия"" Москва - Тверь - Великий Новгород - С...",539.0,0.0,NaN,...,831115fffffffff,8411155ffffffff,85111543fffffff,861115407ffffff,871115405ffffff,8811154019fffff,9,3,100,0
6786,490119585,2018-11-11,16:25:00,"Новгородская область, Окуловский район, Окуловка",Николая Николаева ул,53,NaN,NaN,NaN,Столкновение,...,831113fffffffff,8411115ffffffff,8511114bfffffff,861111487ffffff,87111148effffff,8811114833fffff,11,6,315,0
6787,490109680,2018-09-28,12:45:00,"Новгородская область, Великий Новгород",Кочетова ул,23а,NaN,NaN,NaN,Столкновение,...,831115fffffffff,8411155ffffffff,85111543fffffff,861115427ffffff,871115420ffffff,881115421dfffff,28,4,271,0

Сделаем категории **"Вид ДТП"** и **"Улица"** раноговыми

In [17]:
df_train=df_train.merge(pd.DataFrame(df_train.groupby(['id'])['id'].count()),left_on='id', right_index=True,suffixes=('', '_count'))
df_test=df_test.merge(pd.DataFrame(df_test.groupby(['id'])['id'].count()),left_on='id', right_index=True,suffixes=('', '_count'))

df_test

,id,Дата,Время,Место,Улица,Дом,Дорога,Километр,Метр,Вид ДТП,...,h3-4,h3-5,h3-6,h3-7,h3-8,day,day_of_week,day_of_year,hour,id_count
0,490078911,2018-01-31,19:15:00,"Новгородская область, Великий Новгород",Нехинская ул,59,NaN,NaN,NaN,Столкновение,...,8411155ffffffff,85111543fffffff,861115427ffffff,871115420ffffff,8811154201fffff,31,2,31,0,1
1,490055448,2019-06-19,10:15:00,"Новгородская область, Великий Новгород",Большая Московская ул,38,NaN,NaN,NaN,Столкновение,...,8411155ffffffff,85111543fffffff,861115407ffffff,871115405ffffff,8811154055fffff,19,2,170,0,1
2,490054440,2019-06-28,03:00:00,"Новгородская область, Великий Новгород",NaN,NaN,NaN,NaN,NaN,Наезд на препятствие,...,8411155ffffffff,85111543fffffff,861115407ffffff,871115405ffffff,8811154019fffff,28,4,179,0,1
3,490037847,2019-01-02,13:15:00,"Новгородская область, Великий Новгород",Колмовская наб,3,NaN,NaN,NaN,Наезд на препятствие,...,8411155ffffffff,85111543fffffff,86111542fffffff,87111542effffff,88111542e1fffff,2,2,2,0,1
4,490037049,2019-08-02,10:35:00,"Новгородская область, Окуловский район",NaN,NaN,Нева Москва - Санкт-Петербург (основное направ...,471.0,900.0,Наезд на препятствие,...,8411115ffffffff,8511114bfffffff,86111149fffffff,87111149dffffff,88111149d9fffff,2,4,214,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6783,490014641,2020-11-07,23:15:00,"Новгородская область, Боровичский район, Боровичи",Коммунарная ул,1А,NaN,NaN,NaN,NaN,...,841113bffffffff,851113affffffff,861113ae7ffffff,871113ae0ffffff,881113ae09fffff,7,5,312,0,1
6784,490033115,2020-12-01,15:20:00,"Новгородская область, Окуловский район",NaN,NaN,Нева Москва - Санкт-Петербург (основное направ...,438.0,833.0,NaN,...,8411115ffffffff,8511114bfffffff,86111149fffffff,87111149dffffff,88111149d9fffff,1,1,336,0,1
6785,490008221,2020-04-09,20:05:00,"Новгородская область, Новгородский район",NaN,NaN,"""Россия"" Москва - Тверь - Великий Новгород - С...",539.0,0.0,NaN,...,8411155ffffffff,85111543fffffff,861115407ffffff,871115405ffffff,8811154019fffff,9,3,100,0,1
6786,490119585,2018-11-11,16:25:00,"Новгородская область, Окуловский район, Окуловка",Николая Николаева ул,53,NaN,NaN,NaN,Столкновение,...,8411115ffffffff,8511114bfffffff,861111487ffffff,87111148effffff,8811114833fffff,11,6,315,0,1
6787,490109680,2018-09-28,12:45:00,"Новгородская область, Великий Новгород",Кочетова ул,23а,NaN,NaN,NaN,Столкновение,...,8411155ffffffff,85111543fffffff,861115427ffffff,871115420ffffff,881115421dfffff,28,4,271,0,1

In [18]:
#статистика по гексагонам h3 на тестовой выборке
h3_3=pd.DataFrame(df_train.groupby(['h3-3'])['id'].count())
h3_4=pd.DataFrame(df_train.groupby(['h3-4'])['id'].count())
h3_5=pd.DataFrame(df_train.groupby(['h3-5'])['id'].count())
h3_6=pd.DataFrame(df_train.groupby(['h3-6'])['id'].count())
h3_7=pd.DataFrame(df_train.groupby(['h3-7'])['id'].count())
h3_8=pd.DataFrame(df_train.groupby(['h3-8'])['id'].count())
h3_8

                 id
h3-8
8811025a05fffff   3
8811025b13fffff   1
8811025b1bfffff   3
8811025b29fffff   2
88111008d3fffff   6
...              ..
8811ada4c5fffff   2
8811ada605fffff   7
8811ada629fffff   2
8811ada663fffff   2
8811adb68dfffff   6

[892 rows x 1 columns]

In [19]:

df_train=df_train.merge(h3_3,left_on='h3-3', right_index=True,suffixes=('', '_h3_3'))
df_train=df_train.merge(h3_4,left_on='h3-4', right_index=True,suffixes=('', '_h3_4'))
df_train=df_train.merge(h3_5,left_on='h3-5', right_index=True,suffixes=('', '_h3_5'))
df_train=df_train.merge(h3_6,left_on='h3-6', right_index=True,suffixes=('', '_h3_6'))
df_train=df_train.merge(h3_7,left_on='h3-7', right_index=True,suffixes=('', '_h3_7'))
df_train=df_train.merge(h3_8,left_on='h3-8', right_index=True,suffixes=('', '_h3_8'))

In [20]:
df_test=df_test.merge(h3_3,how="left",left_on='h3-3', right_index=True,suffixes=('', '_h3_3')).fillna(0)
df_test=df_test.merge(h3_4,how="left",left_on='h3-4', right_index=True,suffixes=('', '_h3_4')).fillna(0)
df_test=df_test.merge(h3_5,how="left",left_on='h3-5', right_index=True,suffixes=('', '_h3_5')).fillna(0)
df_test=df_test.merge(h3_6,how="left",left_on='h3-6', right_index=True,suffixes=('', '_h3_6')).fillna(0)
df_test=df_test.merge(h3_7,how="left",left_on='h3-7', right_index=True,suffixes=('', '_h3_7')).fillna(0)
df_test=df_test.merge(h3_8,how="left",left_on='h3-8', right_index=True,suffixes=('', '_h3_8')).fillna(0)

In [21]:
df_test[['Место','Улица','Дом','Дорога']]=df_test[['Место','Улица','Дом','Дорога']].fillna('')
df_train[['Место','Улица','Дом','Дорога']]=df_train[['Место','Улица','Дом','Дорога']].fillna('')

df_test=df_test.fillna(-1)
df_train=df_train.fillna(-1)

Пострим на распределение данных

In [22]:
X = df_train.drop(["Дата", "Время","Место","Дорога", "Дом", "id", "Погибло",	"Погибло детей",	"Ранено",	"Ранено детей"], axis = 1)
y = df_train[["Погибло",	"Погибло детей",	"Ранено",	"Ранено детей"]]

df_test=df_test.drop(["Дата", "Время","Место","Дорога", "Дом"], axis = 1)

In [23]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 35771 entries, 0 to 21504
Data columns (total 23 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Улица        35771 non-null  object
 1   Километр     35771 non-null  float64
 2   Метр         35771 non-null  float64
 3   Вид ДТП      35771 non-null  object
 4   x            35771 non-null  object
 5   y            35771 non-null  object
 6   h3-3         35771 non-null  object
 7   h3-4         35771 non-null  object
 8   h3-5         35771 non-null  object
 9   h3-6         35771 non-null  object
 10  h3-7         35771 non-null  object
 11  h3-8         35771 non-null  object
 12  day          35771 non-null  int64
 13  day_of_week  35771 non-null  int64
 14  day_of_year  35771 non-null  int64
 15  hour         35771 non-null  int64
 16  id_count     35771 non-null  int64
 17  id_h3_3      35771 non-null  int64
 18  id_h3_4      35771 non-null  int64
 19  id_h3_5      35771 non-null  int64
 20  id_h3_6      35771 non-null  int64
 21  id_h3_7      35771 non-null  int64
 22  id_h3_8      35771 non-null  int64
dtypes: float64(2), int64(11), object(10)
memory usage: 6.5+ MB

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

In [25]:
y_train

       Погибло  Погибло детей  Ранено  Ранено детей
29024        0              0       0             0
31256        0              0       0             0
18523        0              0       0             0
9337         0              0       1             0
14498        0              0       0             0
...        ...            ...     ...           ...
8229         0              0       0             0
4786         0              0       0             0
14282        0              0       0             0
3472         0              0       0             0
7953         0              0       1             0

[32193 rows x 4 columns]

## Обучение модели

In [26]:
from catboost import CatBoostRegressor
from catboost import CatBoostClassifier

In [27]:
cat_features=['Улица', 'Вид ДТП','h3-3', 'h3-4','h3-5', 'h3-6', 'h3-7', 'h3-8']

In [28]:
y_train['Погибло'][y_train['Погибло']>0]=1
y_train['Погибло детей'][y_train['Погибло детей']>0]=1
y_train['Ранено'][y_train['Ранено']>0]=1
y_train['Ранено детей'][y_train['Ранено детей']>0]=1

y_test['Погибло'][y_test['Погибло']>0]=1
y_test['Погибло детей'][y_test['Погибло детей']>0]=1
y_test['Ранено'][y_test['Ранено']>0]=1
y_test['Ранено детей'][y_test['Ранено детей']>0]=1

In [29]:
model1 = CatBoostClassifier(iterations=1000,
                          depth=12)
#,eval_metric='BalancedAccuracy'
model1.fit(X_train, y_train['Погибло'],
          cat_features=cat_features,use_best_model=True,early_stopping_rounds=100,
          eval_set=(X_test, y_test['Погибло']),
         plot=True,verbose=False)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

In [30]:
model2 = CatBoostClassifier(iterations=1000,
                          depth=12)
#,eval_metric='BalancedAccuracy'
model2.fit(X_train, y_train['Погибло детей'],
          cat_features=cat_features,use_best_model=True,early_stopping_rounds=100,
          eval_set=(X_test, y_test['Погибло детей']),
         plot=True,verbose=False)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

In [31]:
model3 = CatBoostClassifier(iterations=1000,
                          depth=12)
#,eval_metric='BalancedAccuracy'
model3.fit(X_train, y_train['Ранено'],
          cat_features=cat_features,use_best_model=True,early_stopping_rounds=100,
          eval_set=(X_test, y_test['Ранено']),
         plot=True,verbose=False)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

In [32]:
model4 = CatBoostClassifier(iterations=1000,
                          depth=12)
#,eval_metric='BalancedAccuracy'
model4.fit(X_train, y_train['Ранено детей'],
          cat_features=cat_features,use_best_model=True,early_stopping_rounds=100,
          eval_set=(X_test, y_test['Ранено детей']),
         plot=True,verbose=False)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

In [33]:
df_test

,id,Улица,Километр,Метр,Вид ДТП,x,y,h3-3,h3-4,h3-5,...,day_of_week,day_of_year,hour,id_count,id_h3_3,id_h3_4,id_h3_5,id_h3_6,id_h3_7,id_h3_8
0,490078911,Нехинская ул,0.0,0.0,Столкновение,31.222457,58.524271,831115fffffffff,8411155ffffffff,85111543fffffff,...,2,31,0,1,23696,21808,21191.0,6595.0,877.0,217.0
1,490055448,Большая Московская ул,0.0,0.0,Столкновение,31.289507,58.521757,831115fffffffff,8411155ffffffff,85111543fffffff,...,2,170,0,1,23696,21808,21191.0,9710.0,8976.0,231.0
2,490054440,0,0.0,0.0,Наезд на препятствие,31.308039,58.529252,831115fffffffff,8411155ffffffff,85111543fffffff,...,4,179,0,1,23696,21808,21191.0,9710.0,8976.0,7301.0
3,490037847,Колмовская наб,0.0,0.0,Наезд на препятствие,31.276733,58.541569,831115fffffffff,8411155ffffffff,85111543fffffff,...,2,2,0,1,23696,21808,21191.0,4808.0,2110.0,101.0
4,490037049,0,471.0,900.0,Наезд на препятствие,33.297763,58.376532,831113fffffffff,8411115ffffffff,8511114bfffffff,...,4,214,0,1,5511,1931,1822.0,1476.0,1447.0,1437.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6783,490014641,Коммунарная ул,0.0,0.0,0,33.91769,58.385846,831113fffffffff,841113bffffffff,851113affffffff,...,5,312,0,1,5511,2239,1535.0,1640.0,307.0,139.0
6784,490033115,0,438.0,833.0,0,33.297763,58.376532,831113fffffffff,8411115ffffffff,8511114bfffffff,...,1,336,0,1,5511,1931,1822.0,1476.0,1447.0,1437.0
6785,490008221,0,539.0,0.0,0,31.308039,58.529252,831115fffffffff,8411155ffffffff,85111543fffffff,...,3,100,0,1,23696,21808,21191.0,9710.0,8976.0,7301.0
6786,490119585,Николая Николаева ул,0.0,0.0,Столкновение,33.294502,58.382444,831113fffffffff,8411115ffffffff,8511114bfffffff,...,6,315,0,1,5511,1931,1822.0,64.0,157.0,39.0
6787,490109680,Кочетова ул,0.0,0.0,Столкновение,31.224253,58.535641,831115fffffffff,8411155ffffffff,85111543fffffff,...,4,271,0,1,23696,21808,21191.0,6595.0,877.0,297.0

In [34]:
X_train

,Улица,Километр,Метр,Вид ДТП,x,y,h3-3,h3-4,h3-5,h3-6,...,day_of_week,day_of_year,hour,id_count,id_h3_3,id_h3_4,id_h3_5,id_h3_6,id_h3_7,id_h3_8
29024,,-1.0,-1.0,Столкновение,31.355461,57.99072,831110fffffffff,8411109ffffffff,8511109bfffffff,86111099fffffff,...,0,288,7,2,2744,1017,867,650,589,270
31256,,546.0,0.0,Наезд на препятствие,31.308039,58.529252,831115fffffffff,8411155ffffffff,85111543fffffff,861115407ffffff,...,0,217,9,3,23696,21808,21191,9710,8976,7301
18523,,-1.0,-1.0,Наезд на препятствие,31.308039,58.529252,831115fffffffff,8411155ffffffff,85111543fffffff,861115407ffffff,...,5,202,21,2,23696,21808,21191,9710,8976,7301
9337,,3.0,280.0,Столкновение,31.308039,58.529252,831115fffffffff,8411155ffffffff,85111543fffffff,861115407ffffff,...,5,117,9,3,23696,21808,21191,9710,8976,7301
14498,Большая Санкт-Петербургская ул,-1.0,-1.0,Столкновение,31.264148,58.543236,831115fffffffff,8411155ffffffff,85111543fffffff,86111542fffffff,...,3,151,17,3,23696,21808,21191,4808,2110,755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8229,Коровникова ул,-1.0,-1.0,Столкновение,31.217462,58.54496,831115fffffffff,8411155ffffffff,85111543fffffff,861115427ffffff,...,5,27,18,3,23696,21808,21191,6595,104,198
4786,,12.0,400.0,-1,31.308039,58.529252,831115fffffffff,8411155ffffffff,85111543fffffff,861115407ffffff,...,1,196,9,3,23696,21808,21191,9710,8976,7301
14282,,525.0,900.0,-1,31.308039,58.529252,831115fffffffff,8411155ffffffff,85111543fffffff,861115407ffffff,...,4,129,14,1,23696,21808,21191,9710,8976,7301
3472,Большая Санкт-Петербургская ул,-1.0,-1.0,-1,31.264534,58.541668,831115fffffffff,8411155ffffffff,85111543fffffff,86111542fffffff,...,0,13,11,3,23696,21808,21191,4808,2110,755
7953,Александра Корсунова пр-кт,-1.0,-1.0,Столкновение,31.242669,58.543964,831115fffffffff,8411155ffffffff,85111543fffffff,861115427ffffff,...,2,93,14,3,23696,21808,21191,6595,2044,627

In [35]:
rez=df_test

In [36]:
rez

,id,Улица,Километр,Метр,Вид ДТП,x,y,h3-3,h3-4,h3-5,...,day_of_week,day_of_year,hour,id_count,id_h3_3,id_h3_4,id_h3_5,id_h3_6,id_h3_7,id_h3_8
0,490078911,Нехинская ул,0.0,0.0,Столкновение,31.222457,58.524271,831115fffffffff,8411155ffffffff,85111543fffffff,...,2,31,0,1,23696,21808,21191.0,6595.0,877.0,217.0
1,490055448,Большая Московская ул,0.0,0.0,Столкновение,31.289507,58.521757,831115fffffffff,8411155ffffffff,85111543fffffff,...,2,170,0,1,23696,21808,21191.0,9710.0,8976.0,231.0
2,490054440,0,0.0,0.0,Наезд на препятствие,31.308039,58.529252,831115fffffffff,8411155ffffffff,85111543fffffff,...,4,179,0,1,23696,21808,21191.0,9710.0,8976.0,7301.0
3,490037847,Колмовская наб,0.0,0.0,Наезд на препятствие,31.276733,58.541569,831115fffffffff,8411155ffffffff,85111543fffffff,...,2,2,0,1,23696,21808,21191.0,4808.0,2110.0,101.0
4,490037049,0,471.0,900.0,Наезд на препятствие,33.297763,58.376532,831113fffffffff,8411115ffffffff,8511114bfffffff,...,4,214,0,1,5511,1931,1822.0,1476.0,1447.0,1437.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6783,490014641,Коммунарная ул,0.0,0.0,0,33.91769,58.385846,831113fffffffff,841113bffffffff,851113affffffff,...,5,312,0,1,5511,2239,1535.0,1640.0,307.0,139.0
6784,490033115,0,438.0,833.0,0,33.297763,58.376532,831113fffffffff,8411115ffffffff,8511114bfffffff,...,1,336,0,1,5511,1931,1822.0,1476.0,1447.0,1437.0
6785,490008221,0,539.0,0.0,0,31.308039,58.529252,831115fffffffff,8411155ffffffff,85111543fffffff,...,3,100,0,1,23696,21808,21191.0,9710.0,8976.0,7301.0
6786,490119585,Николая Николаева ул,0.0,0.0,Столкновение,33.294502,58.382444,831113fffffffff,8411115ffffffff,8511114bfffffff,...,6,315,0,1,5511,1931,1822.0,64.0,157.0,39.0
6787,490109680,Кочетова ул,0.0,0.0,Столкновение,31.224253,58.535641,831115fffffffff,8411155ffffffff,85111543fffffff,...,4,271,0,1,23696,21808,21191.0,6595.0,877.0,297.0

In [37]:
rez['Погибло']=(model1.predict(df_test.drop(["id"], axis = 1),prediction_type='Probability')[:,1]>0.1)*1
rez['Погибло детей']=(model2.predict(df_test.drop(["id"], axis = 1),prediction_type='Probability')[:,1]>0.1)*1
rez['Ранено']=(model3.predict(df_test.drop(["id"], axis = 1),prediction_type='Probability')[:,1]>0.5)*1
rez['Ранено детей']=(model4.predict(df_test.drop(["id"], axis = 1),prediction_type='Probability')[:,1]>0.15)*1

In [38]:
#rez['Ранено детей'].value_counts()

In [39]:
#y_train['Ранено детей'].value_counts()

In [40]:
rez

,id,Улица,Километр,Метр,Вид ДТП,x,y,h3-3,h3-4,h3-5,...,id_h3_3,id_h3_4,id_h3_5,id_h3_6,id_h3_7,id_h3_8,Погибло,Погибло детей,Ранено,Ранено детей
0,490078911,Нехинская ул,0.0,0.0,Столкновение,31.222457,58.524271,831115fffffffff,8411155ffffffff,85111543fffffff,...,23696,21808,21191.0,6595.0,877.0,217.0,0,0,0,0
1,490055448,Большая Московская ул,0.0,0.0,Столкновение,31.289507,58.521757,831115fffffffff,8411155ffffffff,85111543fffffff,...,23696,21808,21191.0,9710.0,8976.0,231.0,0,0,0,0
2,490054440,0,0.0,0.0,Наезд на препятствие,31.308039,58.529252,831115fffffffff,8411155ffffffff,85111543fffffff,...,23696,21808,21191.0,9710.0,8976.0,7301.0,0,0,0,0
3,490037847,Колмовская наб,0.0,0.0,Наезд на препятствие,31.276733,58.541569,831115fffffffff,8411155ffffffff,85111543fffffff,...,23696,21808,21191.0,4808.0,2110.0,101.0,0,0,0,0
4,490037049,0,471.0,900.0,Наезд на препятствие,33.297763,58.376532,831113fffffffff,8411115ffffffff,8511114bfffffff,...,5511,1931,1822.0,1476.0,1447.0,1437.0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6783,490014641,Коммунарная ул,0.0,0.0,0,33.91769,58.385846,831113fffffffff,841113bffffffff,851113affffffff,...,5511,2239,1535.0,1640.0,307.0,139.0,1,0,0,0
6784,490033115,0,438.0,833.0,0,33.297763,58.376532,831113fffffffff,8411115ffffffff,8511114bfffffff,...,5511,1931,1822.0,1476.0,1447.0,1437.0,0,0,0,0
6785,490008221,0,539.0,0.0,0,31.308039,58.529252,831115fffffffff,8411155ffffffff,85111543fffffff,...,23696,21808,21191.0,9710.0,8976.0,7301.0,0,0,0,0
6786,490119585,Николая Николаева ул,0.0,0.0,Столкновение,33.294502,58.382444,831113fffffffff,8411115ffffffff,8511114bfffffff,...,5511,1931,1822.0,64.0,157.0,39.0,0,0,0,0
6787,490109680,Кочетова ул,0.0,0.0,Столкновение,31.224253,58.535641,831115fffffffff,8411155ffffffff,85111543fffffff,...,23696,21808,21191.0,6595.0,877.0,297.0,0,0,0,0

In [41]:
rez[['id','Погибло','Погибло детей','Ранено','Ранено детей']]

             id  Погибло  Погибло детей  Ранено  Ранено детей
0     490078911        0              0       0             0
1     490055448        0              0       0             0
2     490054440        0              0       0             0
3     490037847        0              0       0             0
4     490037049        0              0       0             0
...         ...      ...            ...     ...           ...
6783  490014641        1              0       0             0
6784  490033115        0              0       0             0
6785  490008221        0              0       0             0
6786  490119585        0              0       0             0
6787  490109680        0              0       0             0

[6788 rows x 5 columns]

In [42]:
ss=pd.read_csv("./sample_solution.csv")
ss

             id  Погибло  Погибло детей  Ранено  Ранено детей
0     490078911        0              0       0             0
1     490055448        0              0       0             0
2     490054440        0              0       0             0
3     490037847        0              0       0             0
4     490037049        0              0       0             0
...         ...      ...            ...     ...           ...
6783  490014641        0              0       0             0
6784  490033115        0              0       0             0
6785  490008221        0              0       0             0
6786  490119585        0              0       0             0
6787  490109680        0              0       0             0

[6788 rows x 5 columns]

In [43]:
sub=ss.merge(rez,left_on='id',how="left", right_on='id',suffixes=('_', '')).fillna(0)
sub

,id,Погибло_,Погибло детей_,Ранено_,Ранено детей_,Улица,Километр,Метр,Вид ДТП,x,...,id_h3_3,id_h3_4,id_h3_5,id_h3_6,id_h3_7,id_h3_8,Погибло,Погибло детей,Ранено,Ранено детей
0,490078911,0,0,0,0,Нехинская ул,0.0,0.0,Столкновение,31.222457,...,23696,21808,21191.0,6595.0,877.0,217.0,0,0,0,0
1,490055448,0,0,0,0,Большая Московская ул,0.0,0.0,Столкновение,31.289507,...,23696,21808,21191.0,9710.0,8976.0,231.0,0,0,0,0
2,490054440,0,0,0,0,0,0.0,0.0,Наезд на препятствие,31.308039,...,23696,21808,21191.0,9710.0,8976.0,7301.0,0,0,0,0
3,490037847,0,0,0,0,Колмовская наб,0.0,0.0,Наезд на препятствие,31.276733,...,23696,21808,21191.0,4808.0,2110.0,101.0,0,0,0,0
4,490037049,0,0,0,0,0,471.0,900.0,Наезд на препятствие,33.297763,...,5511,1931,1822.0,1476.0,1447.0,1437.0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6783,490014641,0,0,0,0,Коммунарная ул,0.0,0.0,0,33.91769,...,5511,2239,1535.0,1640.0,307.0,139.0,1,0,0,0
6784,490033115,0,0,0,0,0,438.0,833.0,0,33.297763,...,5511,1931,1822.0,1476.0,1447.0,1437.0,0,0,0,0
6785,490008221,0,0,0,0,0,539.0,0.0,0,31.308039,...,23696,21808,21191.0,9710.0,8976.0,7301.0,0,0,0,0
6786,490119585,0,0,0,0,Николая Николаева ул,0.0,0.0,Столкновение,33.294502,...,5511,1931,1822.0,64.0,157.0,39.0,0,0,0,0
6787,490109680,0,0,0,0,Кочетова ул,0.0,0.0,Столкновение,31.224253,...,23696,21808,21191.0,6595.0,877.0,297.0,0,0,0,0

## Оценка точности

In [44]:
sub[['id','Погибло', 'Погибло детей', 'Ранено', 'Ранено детей']].to_csv('sub_p.csv', index=False)

In [45]:
sub[['Погибло', 'Погибло детей', 'Ранено', 'Ранено детей']].sum()

Погибло           59
Погибло детей      0
Ранено           312
Ранено детей      31
dtype: int64

Погибло            0
Погибло детей      0
Ранено           274
Ранено детей       0